### PR TITLE
[Hotfix] Add Pools info into global instance

### PR DESCRIPTION
**Pull request by ccaillot**
## Changelog Description
Add Pools info into global instance in order to have the same pool's parameters for Publish Job.

### CODE REVIEW

**Comment by BenSouchet** [comment]
Haven't yet tested my commit but this should work.

I think we should use `self.get_attr_value(self, instance, "NAME_OF_THE_ATTR", optional_fallback_value)` for retrieving values of instance data in every submitter plugins.

**Comment by BenSouchet** [comment]
And the collect render (`openpype/hosts/maya/plugins/publish/collect_render.py`) should use the `DeadlineDefaultJobAttrs` and `get_deadline_job_profile` if deadline is enabled to set default values for `priority`, `machineLimit`, etc...

**Comment by BenSouchet** [comment]
@ccaillot if you want to take a look tomorrow, I would greatly appreciate :pray:

**Comment by ccaillot** [comment]
@BenSouchet I've pushed some updates which fix little things.

Also, I've decided to delete the collect_pools.py because it will constantly overwrite the `pool` and `pool_secondary` instance.data during the publish process and make the `get_attr_value(plugin, instance, attr_name, fallback=None):` return bad values for both fields. It happens cause of the condition order.  First, we return the attr's value if this one is in the instance.data dict ([l.66 from deadline.utils.py](https://github.com/quadproduction/OpenPype/blob/7a4d91c4045bb8fa6e4e67d69f1f751534b04945/openpype/modules/deadline/utils.py#L66)) and after we return attr values from submitter plugin ([l.69 from deadline_utils.py](https://github.com/quadproduction/OpenPype/blob/7a4d91c4045bb8fa6e4e67d69f1f751534b04945/openpype/modules/deadline/utils.py#L66)).

This order sounds good to me, but if we would like to keep the collect_pools.py, we can reverse this 2 conditions, but as we managed directly the pools data from each submitter in the `get_attribute_defs()`, it make the collect_pools.py totally useless, that's why I decided to delete it.

**Pull request merged**
