### PR TITLE
Improve Status update system

### PR DESCRIPTION
**Pull request by BenSouchet**

### CODE REVIEW

**Comment by louparis** [comment]
#203 : add status on render type instance creator
#250 : Problème Ftrack changement de status automatique
#335 : Ftrack / version status affects task status
#68 : Ftrack / The status should be changed back to "in progress" only if a backup is made.
#247 : add a "pass this version in pending review" checkbox in Nuke "publish on farm" tool

**Comment by BenSouchet** [comment]
Screenshot_2024-02-14_18-32-07

**Comment by BenSouchet** [comment]
@mre7a Can you check if the event callbacks:
```python
# Hooks when a file has been opened or saved
register_event_callback("open", self.after_file_open)
register_event_callback("after.save", self.after_file_save)
```
Added in `openpype/modules/ftrack/ftrack_module.py` are properly triggered for Maya & Nuke.

And checking in a TEST_OP2_PUB or any other test project if the task status update properly as indicated in the mapping set in the settings, see screen and explanations in the previous comment.

**Comment by mre7a** [comment]
It works fine in Maya.  However, I don't think it works for Nuke.

**Comment by BenSouchet** [comment]
> It works fine in Maya. However, I don't think it works for Nuke.

Its seems Nuke use the open event:
```python
register_event_callback("workio.open_file", check_inventory_versions)
```
But don't know the correct event for after save event

**Comment by BenSouchet** [comment]
il semblerait qu'il existe: `workio.open_file` et `workio.save_file` pour tout les hosts, c'est pas un after donc c'est chiant un peu, à voir si `after.workio.open_file` et `after.workio.save_file` marchent ou maybe `workio.open_file.after` et `workio.save_file.after`.

Si tu peux faire des tests @mre7a merci

**Comment by mre7a** [comment]
It's a little confusing as they use `workio.open_file` event in their code, but it does not work in our case. 

I tried to emit `open` for [onscriptload](https://learn.foundry.com/nuke/developers/latest/pythondevguide/callbacks.html#onscriptload) and `after.save` for  
[onscriptsave](https://learn.foundry.com/nuke/developers/latest/pythondevguide/callbacks.html#onscriptsave) myself. It worked for the save, but for open, it works one per nuke launch.

**Comment by mre7a** [comment]
more information on events for nuke: 
When we open a scene via openpye workfile, we have `workfile.open.before` and `workfile.open.after` events, but they don't appear on nuke initialization scene opening. 
When we save as a scene via openpype workfile, we have `workfile.save.before` and `workfile.save.after` events, but they don't appear when we save a scene via nuke file menu.

**Comment by BenSouchet** [comment]
> more information on events for nuke: When we open a scene via openpye workfile, we have `workfile.open.before` and `workfile.open.after` events, but they don't appear on nuke initialization scene opening. When we save as a scene via openpype workfile, we have `workfile.save.before` and `workfile.save.after` events, but they don't appear when we save a scene via nuke file menu.

Do you have access to the OP discord? can you ask about that please

**Comment by mre7a** [comment]
I add their answers below:
1. Maya registers the events here; https://github.com/ynput/OpenPype/blob/develop/openpype/hosts/maya/api/pipeline.py#L112-L125
So you would just need to extend the event registered for Nuke here; https://github.com/ynput/OpenPype/blob/develop/openpype/hosts/nuke/api/pipeline.py#L128-L130

2. Well sort of - we'd still need to ensure that Nuke emits the same signals if it doesn't yet. The `workfile.*` ones come from the Workfile tool itself, so should be fine.
I don't see anywhere in the codebase where `workio.open_file `would be emitted. Is this a bug?
Pretty sure that event callback never triggers.  Should have been `workfile.open.after` maybe? 
And these callbacks -> https://github.com/ynput/OpenPype/blob/e020ca721a73b5950c63224f7577857a16634c6e/openpype/hosts/nuke/api/pipeline.py#L173-L175
Should actually be doing `emit_event` of OpenPype itself so others can hook into it.
These are the ones that do the scene inventory check currently - not the invalid callback name registered above. 
Similar to Maya, Houdini, Fusion, Blender. 

3. Basically the Host integration should hook into the DCC callbacks, and from that emit OpenPype/AYON events like "open", "save", "new", "init" or whatever - preferably using names that are consistent across multiple host integrations. So that if you wanted to set up a global check across all hosts you could just register a global callback to e.g. `"open"`.
Seems Nuke's callback design isn't really up to the OpenPype/AYON standards currently.

**Comment by BenSouchet** [comment]
donc de ce que je comprends il faut ajouter des functions qui vont simplement faire un `emit_event` pour Nuke juste après ça :
https://github.com/ynput/OpenPype/blob/e020ca721a73b5950c63224f7577857a16634c6e/openpype/hosts/nuke/api/pipeline.py#L173-L175

**Comment by BenSouchet** [comment]
@mre7a Pour le moment essayons de faire une equivalence à Maya avec l'ajout de `"open"` et `"after.save"`

**Comment by mre7a** [comment]
For now, we have this situation for the Nuke part:

- The `open` event is fired every time we have a `workfile.open.after` event. This is fired when you open a scene using the Openpype Workfile tool. Opening a scene using the Nuke File menu, Open, does not fire the event. 
Problem: The event is not fired when Nuke is launched. 
 
- The `after.save' event is fired with the Nuke built-in callback (`onScriptSave'). This is fired each time the scene is saved. With the Openpype Workfile tool or with `Ctrl + S`. 
Problem: I see that the event is triggered when nuke starts. This happens because of the way OpenPipe sets the color space.

**Pull request merged**
