### PR TITLE
Fix locked anatomy attributes for project creation

### PR DESCRIPTION
**Pull request by friquette**
## Changelog Description
When creating a new project on Ftrack, the OP attributes were not set with the Prepare Project action due to the protection of the anatomy settings. I added a check of the attributes: if there's new attribute to set, the protection is disabled.

## Testing notes:
1. create a new project on Ftrack
2. do the Prepare Project action on the new project
3. check if the attributes are correctly set

### CODE REVIEW

**Comment by BenSouchet** [comment]
@friquette In my opinion this is not the correct way to fix the issue, your current solution will always bypass the protection every time someone want to edit the project anatomy attributes.
The correct way is to detect if we want to update the attributes because of the prepare project and only allow this operation to bypass the protection

**Comment by BenSouchet** [comment]
Or maybe I haven’t properly understood the protect attrs check that is performed

**Comment by friquette** [comment]
> @friquette In my opinion this is not the correct way to fix the issue, your current solution will always bypass the protection every time someone want to edit the project anatomy attributes. The correct way is to detect if we want to update the attributes because of the prepare project and only allow this operation to bypass the protection

The protection is just a simple condition based on the system settings "Protect Anatomy Attributes" with a `return` if the condition is True. With what I added to the condition, we make sure that a new attribute that were not present in the old attributes can be set correctly by bypassing the system setting. 
Maybe we can add a data in the event data that triggers the function and then see if the data is present in the data ?

**Comment by BenSouchet** [comment]
You just modified the condition so no the IF statement is useless, we now only return if the protection is enabled + there is no modification, so this is equal to no protection.

In your case you are in a specific case where you want to sync to Ftrack , it’s the only time we want that to happen, any others times we want to enter the protection if statement.

So the only way to do that is to detect that we just created a project and we triggered the prepare project action, so in that specific case we can ignore the protect attrs protection

**Pull request merged**
