### PR TITLE
472 enhancement add actions in the builder template

### PR DESCRIPTION
**Pull request by ccaillot**
## Changelog Description
Give the possibility to the user to add Builder Action to Placeholder plugin

## Additional info
I had some issue with the create placeholder when i create it, but seems like my test environment was not good, let me know if it's working for you

## Testing notes:
1. `Git checkout 8-add-actions-to-custom-plugins ` in quad-plugins repo (Clone it if not installed yet)
2. Overwrite the CUSTOM_FIX_PLUGINS Variable in your local settings 
3. Open Maya in a random context
4. OpenPype > Template Builder > Create Placeholder
5. if you select 'Model' in families, you should see 'ActionExemple' in 'Builder Action' field

### CODE REVIEW

**Comment by friquette** [comment]
It seems like there's a problem with the placeholder creation.
When creating a placeholder, I've got this error:
```
# # *** WRN: >>> { WorkfileBuildPlaceholderDialog }: [ Something went wrong ] 
# ==============================
# Unsupported type: <class 'NoneType'>
# ==============================
# Traceback (most recent call last):
#   File "/users_roaming/tfricard/OpenPype/openpype/tools/workfile_template_build/window.py", line 224, in _on_create_click
#     plugin.create_placeholder(options)
#   File "/users_roaming/tfricard/OpenPype/openpype/hosts/maya/api/workfile_template_builder.py", line 191, in create_placeholder
#     # Add helper attributes to keep placeholder info
#   File "/users_roaming/tfricard/OpenPype/openpype/hosts/maya/api/lib.py", line 428, in imprint
#     raise TypeError("Unsupported type: %r" % type(value))
TypeError: Unsupported type: <class 'NoneType'>

```
The action is selected in the interface but it returns nothing.

And I think we should add the possibility of not setting any action because maybe actions are not needed every time on every placeholder ?

**Comment by ccaillot** [comment]
I push new fix, also don't forget to pull the openpype-custom-plugins / quad-plugins ---> '8-add-actions-to-custom-plugins' branch.


image

**Comment by ClementHector** [comment]
@ccaillot Can you resolve the conflict.

**Comment by ccaillot** [comment]
I've solved the conflict but the logic seems to does not work anymore...

**Comment by ccaillot** [comment]
Should be good now :)

**Comment by BenSouchet** [comment]
@ccaillot Peux-tu clean up/remove les edits fait sur les fichiers du dossier `.github` et mettre en source la branch `main` qui est actuellement équivalent à `3.15.12-quad.3.13`, et vérifier si le code marche toujours comme convenu.

**Comment by ccaillot** [comment]
Move this PR to this new [one](https://github.com/quadproduction/OpenPype/pull/596)

**Pull request closed without merging**
